name: CI/CD
run-name: Libs task testing (by @${{ github.actor }})

on:
  create:
  repository_dispatch:
  workflow_dispatch:

jobs:
  buildtest:
    with:
      student_url: ${{ github.repository }}
      student_ref: ${{ github.sha }}
    uses: skkv-cpp/private-tools-2025/.github/workflows/libs.yml@main
    secrets: inherit
