name: Bash Intro Tests

on:
  push:
  workflow_dispatch:

env:
  TASK: bash-intro

jobs:
  buildtest:
    name: BuildTest

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Download tests
        uses: actions/checkout@v4
        with:
          repository: ITMO-OS-LITE/public-tests
          ref: master

      - name: Download student solutions
        uses: actions/checkout@v4
        with:
          path: src
          ref: master

      - name: Test solution
        run: python3 tmain.py --suite ${{ env.TASK }}
